### ISSUE TITLE
Neighbours tab

### ISSUE THREAD

**Issue by DutchGeek** [ThScEo/ForgeOfBot#12]
I see the option to Flood players.  Can you please explain what this does?  If it sends a message to other players that we are using a bot, I don't see the use in this.  This would get your account banned.  

How can I disable this permanently?

**Comment by ThScEo** [comment]
Don't worry, this feature is not enabled and available for users, even if you see it in your panel.
This feature will be available later when all issues would be resolved. This can be used to flood players, eg: advertising etc
