### ISSUE TITLE
GUI's not loading ( white screen )

### ISSUE THREAD

**Issue by Maurice104** [ThScEo/ForgeOfBot#16]
Hello,

I downloaded the newest version of the bot, but now it doesn't even load the GUI. 

For any bugs or issue encountered, please report them with following informations:
Which server are you playing on: Vingrid / Korch
The error output: White Screen
The OS you run: Win10 64bit
The situation when the bug happened: Starting the Bot and logging in 

<a href="https://ibb.co/6gVhCK2"><img src="https://i.ibb.co/vZg5nNb/screen.png" alt="screen" border="0"></a>

**Comment by ThScEo** [comment]
If you have a slow internet connection, please try again and wait few minutes. If it don't loads, let me know.

**Comment by Maurice104** [comment]
I’ve got 100k internet connection, so not really slow. Still after 10 Minutes it’s still white. The bot already worked when I used it few weeks ago, but now it doesn’t work anymore.

**Comment by ThScEo** [comment]
I test the bot on FR servers. I will try to test it on DE servers to resolve the issue. As soon as the issue is resolved i’ll notice you.

**Comment by ThScEo** [comment]
Issue is now resolved. A release will be available in few minutes ;)

**Comment by Maurice104** [comment]
Works so far, thank you :-)

**Comment by huy-lv** [comment]
I downloaded the latest version and still meet the white screen

**Comment by ThScEo** [comment]
The current version of the bot is not compatible. An update will be
published.
